### ISSUE TITLE
[INVESTIGATE] Can we supply a custom root certificate on Windows?

### ISSUE THREAD

**Issue by thepieterdc** [thepieterdc/dodona-plugin-vscode#324]
# Description

Instead of asking the users to ignore the default Windows root certificate, we can maybe supply a custom one instead (https://stackoverflow.com/questions/68896243/how-to-properly-configure-node-js-to-use-self-signed-root-certificates -- not with a self-signed one of course).

Would be a convenient solution for less tech-savvy users

**Comment by bmesuere** [comment]
If the root cause is let's encrypt, it might be simpler to move to our new host name for the plugin. It will be proxied by cloudflare thus using a different non-letsencrypt certificate. Before we rush things we need to confirm some things:
- find someone that can reliably reproduce the issue
- reproduce the issue with a key created on naos.ugent.be and using that as hostname
- using that same key with naos.dodona.be (also proxied by cloudflare) should then work
